# -*- coding: utf-8 -*-
"""nlp_assignment_15.4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-UiCOY1b3-umyHXBUFSWjbPiVKHIRUh

Part A: ELMo + Naive Bayes
"""

import tensorflow_hub as hub
import tensorflow as tf
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

sentences = ["Win money now", "Claim your prize", "Hello how are you",
             "Let's meet tomorrow", "Free lottery ticket", "Are you coming today"]

labels = np.array([1, 1, 0, 0, 1, 0])

elmo = hub.load("https://tfhub.dev/google/elmo/3")

embeddings = elmo.signatures["default"](tf.constant(sentences))["elmo"]

embeddings = elmo.signatures["default"](tf.constant(sentences))["elmo"]
sentence_embeddings = tf.reduce_mean(embeddings, axis=1).numpy()

model_elmo = GaussianNB()
model_elmo.fit(sentence_embeddings, labels)

pred_elmo = model_elmo.predict(sentence_embeddings)
print("ELMo Accuracy:", accuracy_score(labels, pred_elmo))

"""Part B: BERT + Naive Bayes

"""

import tensorflow_hub as hub
import tensorflow_text as text
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

sentences = ["Win money now", "Claim your prize", "Hello how are you",
             "Let's meet tomorrow", "Free lottery ticket", "Are you coming today"]

labels = np.array([1, 1, 0, 0, 1, 0])

preprocess = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

inputs = preprocess(sentences)

outputs = bert(inputs)
sentence_embeddings = outputs["pooled_output"].numpy()

model_bert = GaussianNB()
model_bert.fit(sentence_embeddings, labels)

pred_bert = model_bert.predict(sentence_embeddings)
print("BERT Accuracy:", accuracy_score(labels, pred_bert))

"""Part C: Comparison

"""

from sklearn.metrics import accuracy_score

# --- Accuracy ---
elmo_acc = accuracy_score(labels, pred_elmo)
bert_acc = accuracy_score(labels, pred_bert)

# --- Feature Size ---
elmo_feature_size = sentence_embeddings.shape[1]   # from ELMo
bert_feature_size = 768  # BERT pooled output size

# --- Print Results ---
print("=== Comparison between ELMo and BERT ===\n")

print("Accuracy:")
print("ELMo Accuracy:", elmo_acc)
print("BERT Accuracy:", bert_acc)

print("\nFeature Size:")
print("ELMo Feature Size:", elmo_feature_size)
print("BERT Feature Size:", bert_feature_size)

print("\nObservations:")
if bert_acc >= elmo_acc:
    print("- BERT performs better than ELMo in accuracy.")
else:
    print("- ELMo performs better than BERT.")

print("- BERT captures context bidirectionally.")
print("- ELMo uses LSTM-based embeddings.")
print("- BERT requires more computational power.")
print("- ELMo is faster but less powerful.")

print("\nFinal Conclusion:")
print("BERT outperforms ELMo in terms of accuracy and contextual understanding.")

"""Part D: Testing New Sentences

"""

test_sentences = ["The bat is flying", "He hit the ball with a bat"]

inputs = preprocess(test_sentences)
outputs = bert(inputs)
test_embeddings = outputs["pooled_output"].numpy()

pred_test = model_bert.predict(test_embeddings)

print("Sentences:", test_sentences)
print("Predictions:", pred_test)

sms_sentences = ["Win a free ticket now", "Hello friend how are you",
                 "Claim your prize", "Let's go for lunch"]

sms_labels = np.array([1, 0, 1, 0])

inputs_sms = preprocess(sms_sentences)

outputs_sms = bert(inputs_sms)
sms_embeddings = outputs_sms["pooled_output"].numpy()

model_sms = GaussianNB()
model_sms.fit(sms_embeddings, sms_labels)

pred_sms = model_sms.predict(sms_embeddings)

from sklearn.metrics import accuracy_score
print("SMS Accuracy:", accuracy_score(sms_labels, pred_sms))

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model.fit(sentence_embeddings, labels)

pred_lr = lr_model.predict(sentence_embeddings)

from sklearn.metrics import accuracy_score
print("Logistic Regression Accuracy:", accuracy_score(labels, pred_lr))

from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(sentence_embeddings, labels)

pred_svm = svm_model.predict(sentence_embeddings)

from sklearn.metrics import accuracy_score
print("SVM Accuracy:", accuracy_score(labels, pred_svm))